# This is a basic workflow to help you get started with Actions

name: BuildLinux Rootfs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Package
      run: sudo apt update && sudo apt install debootstrap && arch && sleep 1

    # Runs a set of commands using the runners shell
    - name: Start Build
      run: |
        mkdir rootfs
        sudo debootstrap --arch=amd64 focal rootfs
        cd rootfs && ls -l && cd ..
    # Runs a set of commands using the runners shell
    - name: Save Rootfs
      run: |
        mkdir rootfs
        sudo debootstrap --arch=amd64 focal rootfs
        cd rootfs && ls -l && cd ..
      # Runs a set of commands using the runners shell
    - name: Save Rootfs
      run: |
        tar -czvf rootfs.tar.gz rootfs
