# This is a basic workflow to help you get started with Actions

name: BuildLinux Rootfs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ARCH: amd64
  version: focal

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Core Packages
      run: sudo apt update && sudo apt install debootstrap neofetch -y && neofetch && sleep 1

    # Runs a set of commands using the runners shell
    - name: Building Rootfs
      run: |
        mkdir rootfs
        sudo debootstrap --arch=$ARCH $version rootfs
        cd rootfs && ls -l && cd ..
      # Runs a set of commands using the runners shell
    - name: Saving Rootfs
      run: |
        sudo tar -czvf rootfs.tar.gz rootfs
    - name: Uploading Rootfs
      run: |
       curl -sL https://git.io/file-transfer | sh
       ./transfer wet rootfs.tar.gz
